services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - LOG_LEVEL=info
      - JWT_SECRET=please_change_me_32_chars_minimum
      - JWT_EXPIRES_IN=1h
    volumes:
      - .:/app
      - /app/node_modules
